repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.14.4
    hooks:
      - id: ansible-lint
        files: ^.\/ansible\/.+.(yaml|yml)$
        entry: make lint
