---
- name: Configure Fedora workstation
  hosts: workstation

  tasks:
    - name: Add RPM based repositories
      ansible.builtin.include_tasks: tasks/add_repos.yml

    - name: Peform global system wide setup
      ansible.builtin.include_tasks: tasks/global_setup.yml

    - name: Manage RPM packages
      ansible.builtin.include_tasks: tasks/rpm_packages.yml

    - name: Managed systemd services
      ansible.builtin.include_tasks: tasks/services.yml

    - name: Install jetbrains toolbox
      ansible.builtin.include_tasks: tasks/jetbrains_toolbox.yml

    - name: Directory and file management
      ansible.builtin.include_tasks: tasks/files.yml
