---
- name: Workstation Setup
  hosts: workstation

  vars_files:
    - vars/main.yml

  tasks:
    - include_tasks: tasks/remove_packages.yml
    - include_tasks: tasks/install_repositories.yml
    - include_tasks: tasks/install_packages.yml
    - include_tasks: tasks/install_jetbrains_toolbox.yml
    - include_tasks: tasks/start_services.yml
    - include_tasks: tasks/settings.yml