---
- name: Workstation Setup
  hosts: workstation

  tasks:
    - include_tasks: tasks/remove_packages.yml
    - include_tasks: tasks/install_repositories.yml
    - include_tasks: tasks/install_packages.yml