---
- name: Workstation Setup
  hosts: workstation
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Perform system initialization
      import_role:
        name: initialize

    - name: Perform system package management (install packages)
      import_role:
        name: package_mgmt

    - name: Perform python setup
      import_role:
        name: python_setup

    - include_tasks: tasks/install_jetbrains_toolbox.yml
      tags:
        - install_jetbrains_toolbox

    - include_tasks: tasks/start_services.yml
      tags:
        - start_services

    - include_tasks: tasks/settings.yml
      tags:
        - system_settings
