---
- name: Workstation Setup
  hosts: workstation
  become: true

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  tasks:
    - name: Perform system initialization
      import_role:
        name: initialize

    - include_tasks: tasks/install_packages.yml
      tags:
        - install_packages
        - install_vagrant

    - include_tasks: tasks/install_flatpak_packages.yml
      tags:
        - install_flatpak_packages

    - include_tasks: tasks/install_python_packages.yml
      tags:
        - install_python_packages

    - include_tasks: tasks/install_jetbrains_toolbox.yml
      tags:
        - install_jetbrains_toolbox

    - include_tasks: tasks/start_services.yml
      tags:
        - start_services

    - include_tasks: tasks/settings.yml
      tags:
        - system_settings

    - include_tasks: tasks/install_vagrant_libvirt.yml
      tags:
        - vagrant_libvirt_plugin