---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - asciinema
    - beaker-client
    - code
    - copr-cli
    - copr-rpmbuild
    - docker-ce
    - f28-backgrounds-extras-gnome
    - flatpak
    - gcc
    - git
    - git-cola
    - gitg
    - google-chrome-stable
    - gnome-tweak-tool
    - hexchat
    - krb5-workstation
    - libffi
    - libffi-devel
    - libvirt
    - libvirt-devel
    - libxml2-devel
    - libxslt-devel
    - make
    - openssl
    - openssl-devel
    - pipenv
    - python2-cryptography
    - python2-devel
    - python2-ipython
    - python2-libselinux
    - python3-devel
    - python3-ipython
    - python3-libselinux
    - qemu
    - qemu-kvm
    - redhat-rpm-config
    - remmina
    - ruby
    - ruby-devel
    - tilix
    - tree
    - vim-enhanced
    - virt-install
    - virt-manager
    - virt-viewer
  tags:
    - install_packages

- name: Download vagrant rpm
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}
    /vagrant_{{ vagrant_version }}_x86_64.rpm"
    dest: .
  tags:
    - install_vagrant

- name: Install vagrant
  dnf:
    name: ./vagrant_{{ vagrant_version }}_86_64.rpm
    state: latest
  tags:
    - install_vagrant

- name: Remove vagrant rpm
  file:
    path: ./vagrant_{{ vagrant_version }}_86_64.rpm
    state: absent
  tags:
    - install_vagrant