---
- name: Install Python packages @ root space
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - virtualenv
  tags:
    - install_python_packages

- name: Install Python packages @ user space
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "--user"
  loop:
    - virtualenvwrapper
  tags:
    - install_python_packages
