---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - code
    - docker-ce
    - gcc
    - git
    - google-chrome-stable
    - gnome-tweak-tool
    - hexchat
    - krb5-workstation
    - libffi
    - libffi-devel
    - make
    - openssl
    - openssl-devel
    - python2-devel
    - python2-libselinux
    - python3-devel
    - python3-libselinux
    - redhat-rpm-config
    - tree