---
- name: Remove previous go installation
  ansible.builtin.file:
    path: "/usr/local/go"
    state: directory
    mode: "0755"
  become: true

- name: Install go
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: true
  become: true
