---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - code
    - copr-cli
    - copr-rpmbuild
    - docker-ce
    - gcc
    - git
    - google-chrome-stable
    - gnome-tweak-tool
    - hexchat
    - krb5-workstation
    - libffi
    - libffi-devel
    - make
    - openssl
    - openssl-devel
    - python2-cryptography
    - python2-devel
    - python2-libselinux
    - python3-devel
    - python3-libselinux
    - redhat-rpm-config
    - tree
    - vim-enhanced
  tags:
    - install_packages

- name: Install vagrant
  dnf:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}
    /vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: latest
  tags:
    - install_packages
