---
- block:
    - name: Uninstall packages
      ansible.builtin.dnf:
        name:
          - cheese
          - gnome-calendar
          - gnome-contacts
          - gnome-maps
          - rhythmbox
          - simple-scan
        state: absent

    - name: Install packages
      ansible.builtin.dnf:
        name:
          - asciinema
          - code
          - copr-cli
          - copr-rpmbuild
          - gcc
          - git
          - git-crypt
          - google-chrome-stable
          - gnome-tweak-tool
          - hexchat
          - jq
          - krb5-workstation
          - krb5-devel
          - libffi
          - libffi-devel
          - libvirt
          - libvirt-devel
          - libxml2-devel
          - libxslt-devel
          - make
          - openssl
          - openssl-devel
          - podman
          - python36
          - python3-devel
          - python3-ipython
          - python3-libselinux
          - python3-openstackclient
          - qemu
          - qemu-kvm
          - redhat-rpm-config
          - tilix
          - tigervnc
          - tree
          - vim-enhanced
          - virt-install
          - virt-manager
          - virt-viewer
  become: true
