---

- name: Install rpm packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - asciinema
    - code
    - copr-cli
    - copr-rpmbuild
    - docker-ce
    - flatpak
    - gcc
    - git
    - google-chrome-stable
    - gnome-tweak-tool
    - groovy
    - hexchat
    - krb5-workstation
    - krb5-devel
    - libffi
    - libffi-devel
    - libvirt
    - libvirt-devel
    - libxml2-devel
    - libxslt-devel
    - make
    - openssl
    - openssl-devel
    - python3-devel
    - python3-ipython
    - python3-libselinux
    - python3-openstackclient
    - qemu
    - qemu-kvm
    - redhat-rpm-config
    - ruby
    - ruby-devel
    - tilix
    - tigervnc
    - tree
    - vagrant-libvirt
    - vim-enhanced
    - virt-install
    - virt-manager
    - virt-viewer
  tags:
    - install-rpm-packages
    - install-packages

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.spotify.Client
  tags:
    - install-flatpak-packages
    - install-packages
