---
ansible_connection: local
ansible_python_interpreter: /usr/bin/python3

# default user
default_user: rywillia

# hostname
hostname: laptop

# jetbrains toolbox
jetbrains_toolbox: "jetbrains-toolbox-1.18.7609"

# groups to create
custom_groups:
  - libvirt

# services
services:
  - cups-browsed
  - libvirtd

# python virtual environment directory
python_venv_dirname: .envs
